name: CI - Validação das DAGs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow flake8
      - name: Lint nas DAGs
        run: flake8 dags/
      - name: Validar importação das DAGs
        run: |
          for dag in dags/*.py; do
            python "$dag" || exit 1
          done
